conn salary_mgmt/dbase@xe;
CREATE OR REPLACE PROCEDURE run_enm_address
-- http://182.70.219.212:8080/apex/salary_mgmt.run_enm_address
AS

BEGIN
page_formatting('BEFORE');
	HTP.HTMLOPEN;
		HTP.HEADOPEN;
			HTP.TITLE('MAINTAIN EMPLOYEES ADDRESS');
		HTP.HEADCLOSE;
		HTP.BODYOPEN;
			HTP.FORMOPEN ('http://182.70.219.212:8080/apex/salary_mgmt.salary_manager.enter_and_maintain_address', 'POST');
					HTP.TABLEOPEN;
					HTP.TABLEROWOPEN; 
						HTP.TABLEDATA ('EMPLOYEE ID'); 
						HTP.TABLEDATA (HTF.FORMTEXT('P_EMPLOYEE_ID',NULL,NULL,NULL)); 
					HTP.TABLEROWCLOSE;
					HTP.TABLEROWOPEN; 
						HTP.TABLEDATA ('ADDRESS_1'); 
						HTP.TABLEDATA (HTF.FORMTEXT('p_address_1',NULL,NULL,NULL)); 
					HTP.TABLEROWCLOSE;
					HTP.TABLEROWOPEN; 
						HTP.TABLEDATA ('ADDRESS_2'); 
						HTP.TABLEDATA (HTF.FORMTEXT('p_address_2',NULL,NULL,NULL)); 
					HTP.TABLEROWCLOSE;
					HTP.TABLEROWOPEN; 
						HTP.TABLEDATA ('ADDRESS_3'); 
						HTP.TABLEDATA (HTF.FORMTEXT('p_address_3',NULL,NULL,NULL)); 
					HTP.TABLEROWCLOSE;
					HTP.TABLEROWOPEN; 
						HTP.TABLEDATA ('CITY'); 
						HTP.TABLEDATA (HTF.FORMTEXT('p_city',NULL,NULL,NULL)); 
					HTP.TABLEROWCLOSE;
					HTP.TABLEROWOPEN; 
						HTP.TABLEDATA ('PINCODE'); 
						HTP.TABLEDATA (HTF.FORMTEXT('p_pincode',NULL,NULL,NULL)); 
					HTP.TABLEROWCLOSE;
					HTP.TABLEROWOPEN; 
						HTP.TABLEDATA ('STATE'); 
						HTP.TABLEDATA (HTF.FORMTEXT('p_state',NULL,NULL,NULL)); 
					HTP.TABLEROWCLOSE;
					HTP.TABLEROWOPEN; 
						HTP.TABLEDATA ('COUNTRY'); 
						HTP.TABLEDATA (HTF.FORMTEXT('p_country',NULL,NULL,NULL)); 
					HTP.TABLEROWCLOSE;
					HTP.TABLEROWOPEN; 
						HTP.TABLEDATA ('ADDRESS_TYPE '); 
						HTP.TABLEDATA (HTF.FORMTEXT('p_address_type ',NULL,NULL,NULL)); 
					HTP.TABLEROWCLOSE;
					HTP.TABLEROWOPEN; 
						HTP.TABLEDATA ('MODE'); 
						HTP.TABLEDATA (HTF.FORMTEXT('p_mode',NULL,NULL,NULL)); 
					HTP.TABLEROWCLOSE;
					
				HTP.TABLECLOSE; 
			HTP.FORMCLOSE; 
		HTP.BODYCLOSE;
	HTP.HTMLCLOSE;	
page_formatting('AFTER');
END run_enm_address;
/
GRANT EXECUTE ON salary_mgmt.run_enm_employees TO ANONYMOUS;
SHOW ERROR;
